const gallery = document.querySelector(".gallery");
let lightBox = document.querySelector(".lightbox");
let lightBoxImage = document.getElementById("lightbox-image");
let closeBtn = document.getElementById("close-btn");

const images = [
  "404-page_not_found.png",
  "ai-machine.png",
  "Anime-City-Night.png",
  "Anime-Girl-Rain.png",
  "Anime-Girl1.png",
  "Anime-Girl2.png",
  "Anime-Girl3.png",
  "Anime-Girl4.png",
  "Anime-Girl5.png",
  "Anime-Japan-Street.png",
  "Anime-Purple-eyes.png",
  "Anime-Room.png",
  "Arcade_decay_red.png",
  "Arch-chan_to.png",
  "Backyard.png",
  "Balcony-ja.png",
  "Beach-Dark.png",
  "Beach_light.png",
  "Beer-Girl.png",
  "blackwhole.png",
  "bloodrock-steppes.png",
  "Bonsai-Plant.png",
  "Buildings.png",
  "Candle-Photo.png",
  "Cartoon.png",
  "City-Night.png",
  "City-Rain.png",
  "city-rain.png",
  "City-Rainy-Night.png",
  "city-sundown.png",
  "City_dark.png",
  "City_light.png",
  "Classroom.png",
  "Coffee-1.png",
  "Coffee-2.png",
  "Concept-Japanese house.png",
  "corndog.png",
  "Courtside-Sunset.png",
  "Crater.png",
  "CuteCat.png",
  "Dark_Nature.png",
  "depechemode-violator.png",
  "Dessert-Dark.png",
  "Dessert_light.png",
  "Dreamy-Aesthetic-Home-Under-Moonlight.png",
  "Evangelion.png",
  "explorer-robot.png",
  "Fantasy - Sunset.png",
  "Fantasy-Autumn.png",
  "Fantasy-Garden.png",
  "Fantasy-Hongkong.png",
  "Fantasy-IcyMountain.png",
  "Fantasy-Japanese-Street.png",
  "Fantasy-Lake1.png",
  "Fantasy-Lake2.png",
  "Fantasy-Lake3.png",
  "Fantasy-Landscape1.png",
  "Fantasy-Landscape2.png",
  "Fantasy-Landscape3.png",
  "Fantasy-Lanscape-Night.png",
  "Fantasy-Medieval_Travern.png",
  "Fantasy-Mountain.png",
  "Fantasy-Snow-Valley.png",
  "Fantasy-Waterfall.png",
  "Flower-1.png",
  "Flower-2.png",
  "Flower-3.png",
  "Fog-Forest-Everforest.png",
  "Forest-Dark.png",
  "Forest-Light.png",
  "Fuji-Dark.png",
  "Fuji_light.png",
  "Game-GTA.png",
  "Garden-Dark.png",
  "Garden-Light.png",
  "highway_dark.png",
  "highway_light.png",
  "honkadaloonga.png",
  "italy.png",
  "IT_guy.png",
  "japan-street-Dark.png",
  "japan-street-Light.png",
  "kali-actiniaria-16x9.png",
  "kali-ascii-16x9.png",
  "kali-contours-16x9.png",
  "kali-geometric-16x9.png",
  "kali-layers-16x9.png",
  "kali-legacy-16x9.png",
  "kali-light-strips-16x9.png",
  "kali-neon-16x9.png",
  "kali-nova-16x9.png",
  "kali-small-logo2-16x9.png",
  "kali-strips-16x9.png",
  "kali-trail-16x9.png",
  "kitty_dark.png",
  "kitty_light.png",
  "Lady-Dark.png",
  "Lady-Light.png",
  "Lady.png",
  "Lake.png",
  "Linux-user-Room.png",
  "Lofi - Anime Girl2.png",
  "Lofi - Chill Room.png",
  "Lofi - Study.png",
  "Lofi-Anime-Room.png",
  "Lofi-Cafe1.png",
  "Lofi-Cafe2.png",
  "Lofi-Computer.png",
  "Lofi-Desktop-Man-Studying.png",
  "Lofi-Kitchen.png",
  "Lofi-Room.png",
  "Lofi-Urban-Nightscape.png",
  "Lofi_Cat.png",
  "Lowpoly_Street.png",
  "Manga-Girl-Rain.png",
  "Manga-Portal.png",
  "Manga-Shrine.png",
  "marina-bay-sands.png",
  "Mecha-Nostalgia.png",
  "Minimal_Squares.png",
  "Mountain.png",
  "Mountain_dark.png",
  "Mountain_light.png",
  "Nature - Concept Butterflies.png",
  "Nature - Flower.png",
  "Nature - Lake.png",
  "Nature.png",
  "Night_City.png",
  "Nocturne-of-Steel-and-Glass.png",
  "Northern Lights3.png",
  "Northern Lights6.png",
  "onyx-flow.png",
  "Pastel-Window.png",
  "Patterns.png",
  "pitstop.png",
  "pitstop2.png",
  "plasmawaves.png",
  "Pstel-Window.png",
  "Red_Eclipse.png",
  "Relaxed_Mario.png",
  "Resthouse.png",
  "retro-truck.png",
  "Riding in a bus.png",
  "River.png",
  "Riverside-Dark.png",
  "Riverside_light.png",
  "robot-home.png",
  "room-dark.png",
  "Scifi-Room.png",
  "snowy-peace.png",
  "Solitary-Glow.png",
  "Space-Nebula.png",
  "space-with-ships.png",
  "spaceshuttle.png",
  "Staircase.png",
  "Street-1.png",
  "Street-2.png",
  "Study-table.png",
  "Summer-Mojito.png",
  "Summer-Scene-Dark.png",
  "Summer-Scene-Light.png",
  "Sun-Setting-Horizon.png",
  "sunset-01.png",
  "Sunset-Forrest.png",
  "Sunset-room.png",
  "Techno-Geek.png",
  "the-snap-hunt-camping.png",
  "the-sphere.png",
  "the-sphere2.png",
  "Tokyo_Pink.png",
  "Tower-Night.png",
  "Tree_dark.png",
  "Tree_light.png",
  "Under_Starlit_Sky.png",
  "Village-Dark.png",
  "Village-Light.png",
  "winter-is-here.png",
];

// create and append images
images.forEach((name) => {
  const img = document.createElement("img");
  img.src = "./images/" + name;
  img.classList.add("gallery-item");
  img.loading = "lazy";

  // random size between 300–400
  const randomSize = Math.floor(Math.random() * (400 - 300 + 1)) + 300;
  img.style.width = `${randomSize}px`;
  img.style.height = `${randomSize}px`;

  // add click event for lightbox
  img.addEventListener("click", () => {
    lightBox.style.display = "flex";
    lightBoxImage.src = img.src.replace("-thumbnail", ""); // only needed if thumbnails exist
  });

  gallery.appendChild(img);
});

// close lightbox
closeBtn.addEventListener("click", () => {
  lightBox.style.display = "none";
});
lightBox.addEventListener("click", () => {
  lightBox.style.display = "none";
});
